/*****************************************************************************************************************************/
/* RTICANMM_MAIN_CAN_Arduino_RX_PORT */
/*                                                                                                                           */
/*   AUTHOR(S):                                                                                                              */
/*      U. Homann                                                                                                              */
/*      M. Eikermann                                                                                                              */
/*                                                                                                                           */
/*                                                                                                                           */
/*   RTICANMM Date: 13-Mar-2014 10:38:34                                                                                     */
/*   RTICANMM Version: 3.0.735671.4434490741                                                                                     */
/*                                                                                                                           */
/*  (c) Copyright 2015, dSPACE GmbH. All rights reserved.                                                                    */
/*      Brand names or product names are trademarks or registered trademarks of their respective companies or organizations. */
/*                                                                                                                           */
/* ***************************************************************************************************************************/

/* RTICANMMFreeRawMessage_1.RAW_Byte_1 */ 
ssSetOutputPortDataType(S, 0, SS_UINT8); 
ssSetOutputPortWidth(S, 0, 1); 
/* RTICANMMFreeRawMessage_1.RAW_Byte_2 */ 
ssSetOutputPortDataType(S, 1, SS_UINT8); 
ssSetOutputPortWidth(S, 1, 1); 
/* RTICANMMFreeRawMessage_1.RAW_Byte_3 */ 
ssSetOutputPortDataType(S, 2, SS_UINT8); 
ssSetOutputPortWidth(S, 2, 1); 
/* RTICANMMFreeRawMessage_1.RAW_Byte_4 */ 
ssSetOutputPortDataType(S, 3, SS_UINT8); 
ssSetOutputPortWidth(S, 3, 1); 
/* RTICANMMFreeRawMessage_1.RAW_Byte_5 */ 
ssSetOutputPortDataType(S, 4, SS_UINT8); 
ssSetOutputPortWidth(S, 4, 1); 
/* RTICANMMFreeRawMessage_1.RAW_Byte_6 */ 
ssSetOutputPortDataType(S, 5, SS_UINT8); 
ssSetOutputPortWidth(S, 5, 1); 
/* RTICANMMFreeRawMessage_1.RAW_Byte_7 */ 
ssSetOutputPortDataType(S, 6, SS_UINT8); 
ssSetOutputPortWidth(S, 6, 1); 
/* RTICANMMFreeRawMessage_1.RAW_Byte_8 */ 
ssSetOutputPortDataType(S, 7, SS_UINT8); 
ssSetOutputPortWidth(S, 7, 1); 
/* CAPTURE MESSAGES 1*/ 
ssSetOutputPortDataType(S, 8, SS_BOOLEAN); 
ssSetOutputPortWidth(S, 8, 1); 
ssSetOutputPortDataType(S, 9, SS_DOUBLE); 
ssSetOutputPortWidth(S, 9, 1); 
ssSetOutputPortDataType(S, 10, SS_UINT32); 
ssSetOutputPortWidth(S, 10, 1); 
ssSetOutputPortDataType(S, 11, SS_UINT8); 
ssSetOutputPortWidth(S, 11, 1); 
ssSetOutputPortDataType(S, 12, SS_UINT8); 
ssSetOutputPortWidth(S, 12, 1); 
ssSetOutputPortDataType(S, 13, SS_UINT8); 
ssSetOutputPortWidth(S, 13, 1); 
ssSetOutputPortDataType(S, 14, SS_UINT8); 
ssSetOutputPortWidth(S, 14, 1); 
ssSetOutputPortDataType(S, 15, SS_UINT8); 
ssSetOutputPortWidth(S, 15, 1); 
ssSetOutputPortDataType(S, 16, SS_UINT8); 
ssSetOutputPortWidth(S, 16, 1); 
ssSetOutputPortDataType(S, 17, SS_UINT8); 
ssSetOutputPortWidth(S, 17, 1); 
ssSetOutputPortDataType(S, 18, SS_UINT8); 
ssSetOutputPortWidth(S, 18, 1); 
ssSetOutputPortDataType(S, 19, SS_UINT8); 
ssSetOutputPortWidth(S, 19, 1); 
ssSetOutputPortDataType(S, 20, SS_UINT8); 
ssSetOutputPortWidth(S, 20, 1); 
/* CAPTURE MESSAGES 2*/ 
ssSetOutputPortDataType(S, 21, SS_BOOLEAN); 
ssSetOutputPortWidth(S, 21, 1); 
ssSetOutputPortDataType(S, 22, SS_DOUBLE); 
ssSetOutputPortWidth(S, 22, 1); 
ssSetOutputPortDataType(S, 23, SS_UINT32); 
ssSetOutputPortWidth(S, 23, 1); 
ssSetOutputPortDataType(S, 24, SS_UINT8); 
ssSetOutputPortWidth(S, 24, 1); 
ssSetOutputPortDataType(S, 25, SS_UINT8); 
ssSetOutputPortWidth(S, 25, 1); 
ssSetOutputPortDataType(S, 26, SS_UINT8); 
ssSetOutputPortWidth(S, 26, 1); 
ssSetOutputPortDataType(S, 27, SS_UINT8); 
ssSetOutputPortWidth(S, 27, 1); 
ssSetOutputPortDataType(S, 28, SS_UINT8); 
ssSetOutputPortWidth(S, 28, 1); 
ssSetOutputPortDataType(S, 29, SS_UINT8); 
ssSetOutputPortWidth(S, 29, 1); 
ssSetOutputPortDataType(S, 30, SS_UINT8); 
ssSetOutputPortWidth(S, 30, 1); 
ssSetOutputPortDataType(S, 31, SS_UINT8); 
ssSetOutputPortWidth(S, 31, 1); 
ssSetOutputPortDataType(S, 32, SS_UINT8); 
ssSetOutputPortWidth(S, 32, 1); 
ssSetOutputPortDataType(S, 33, SS_UINT8); 
ssSetOutputPortWidth(S, 33, 1); 
/* CAPTURE MESSAGES 3*/ 
ssSetOutputPortDataType(S, 34, SS_BOOLEAN); 
ssSetOutputPortWidth(S, 34, 1); 
ssSetOutputPortDataType(S, 35, SS_DOUBLE); 
ssSetOutputPortWidth(S, 35, 1); 
ssSetOutputPortDataType(S, 36, SS_UINT32); 
ssSetOutputPortWidth(S, 36, 1); 
ssSetOutputPortDataType(S, 37, SS_UINT8); 
ssSetOutputPortWidth(S, 37, 1); 
ssSetOutputPortDataType(S, 38, SS_UINT8); 
ssSetOutputPortWidth(S, 38, 1); 
ssSetOutputPortDataType(S, 39, SS_UINT8); 
ssSetOutputPortWidth(S, 39, 1); 
ssSetOutputPortDataType(S, 40, SS_UINT8); 
ssSetOutputPortWidth(S, 40, 1); 
ssSetOutputPortDataType(S, 41, SS_UINT8); 
ssSetOutputPortWidth(S, 41, 1); 
ssSetOutputPortDataType(S, 42, SS_UINT8); 
ssSetOutputPortWidth(S, 42, 1); 
ssSetOutputPortDataType(S, 43, SS_UINT8); 
ssSetOutputPortWidth(S, 43, 1); 
ssSetOutputPortDataType(S, 44, SS_UINT8); 
ssSetOutputPortWidth(S, 44, 1); 
ssSetOutputPortDataType(S, 45, SS_UINT8); 
ssSetOutputPortWidth(S, 45, 1); 
ssSetOutputPortDataType(S, 46, SS_UINT8); 
ssSetOutputPortWidth(S, 46, 1); 
/* CAPTURE MESSAGES 4*/ 
ssSetOutputPortDataType(S, 47, SS_BOOLEAN); 
ssSetOutputPortWidth(S, 47, 1); 
ssSetOutputPortDataType(S, 48, SS_DOUBLE); 
ssSetOutputPortWidth(S, 48, 1); 
ssSetOutputPortDataType(S, 49, SS_UINT32); 
ssSetOutputPortWidth(S, 49, 1); 
ssSetOutputPortDataType(S, 50, SS_UINT8); 
ssSetOutputPortWidth(S, 50, 1); 
ssSetOutputPortDataType(S, 51, SS_UINT8); 
ssSetOutputPortWidth(S, 51, 1); 
ssSetOutputPortDataType(S, 52, SS_UINT8); 
ssSetOutputPortWidth(S, 52, 1); 
ssSetOutputPortDataType(S, 53, SS_UINT8); 
ssSetOutputPortWidth(S, 53, 1); 
ssSetOutputPortDataType(S, 54, SS_UINT8); 
ssSetOutputPortWidth(S, 54, 1); 
ssSetOutputPortDataType(S, 55, SS_UINT8); 
ssSetOutputPortWidth(S, 55, 1); 
ssSetOutputPortDataType(S, 56, SS_UINT8); 
ssSetOutputPortWidth(S, 56, 1); 
ssSetOutputPortDataType(S, 57, SS_UINT8); 
ssSetOutputPortWidth(S, 57, 1); 
ssSetOutputPortDataType(S, 58, SS_UINT8); 
ssSetOutputPortWidth(S, 58, 1); 
ssSetOutputPortDataType(S, 59, SS_UINT8); 
ssSetOutputPortWidth(S, 59, 1); 
/* CAPTURE MESSAGES 5*/ 
ssSetOutputPortDataType(S, 60, SS_BOOLEAN); 
ssSetOutputPortWidth(S, 60, 1); 
ssSetOutputPortDataType(S, 61, SS_DOUBLE); 
ssSetOutputPortWidth(S, 61, 1); 
ssSetOutputPortDataType(S, 62, SS_UINT32); 
ssSetOutputPortWidth(S, 62, 1); 
ssSetOutputPortDataType(S, 63, SS_UINT8); 
ssSetOutputPortWidth(S, 63, 1); 
ssSetOutputPortDataType(S, 64, SS_UINT8); 
ssSetOutputPortWidth(S, 64, 1); 
ssSetOutputPortDataType(S, 65, SS_UINT8); 
ssSetOutputPortWidth(S, 65, 1); 
ssSetOutputPortDataType(S, 66, SS_UINT8); 
ssSetOutputPortWidth(S, 66, 1); 
ssSetOutputPortDataType(S, 67, SS_UINT8); 
ssSetOutputPortWidth(S, 67, 1); 
ssSetOutputPortDataType(S, 68, SS_UINT8); 
ssSetOutputPortWidth(S, 68, 1); 
ssSetOutputPortDataType(S, 69, SS_UINT8); 
ssSetOutputPortWidth(S, 69, 1); 
ssSetOutputPortDataType(S, 70, SS_UINT8); 
ssSetOutputPortWidth(S, 70, 1); 
ssSetOutputPortDataType(S, 71, SS_UINT8); 
ssSetOutputPortWidth(S, 71, 1); 
ssSetOutputPortDataType(S, 72, SS_UINT8); 
ssSetOutputPortWidth(S, 72, 1); 
/* CAPTURE MESSAGES 6*/ 
ssSetOutputPortDataType(S, 73, SS_BOOLEAN); 
ssSetOutputPortWidth(S, 73, 1); 
ssSetOutputPortDataType(S, 74, SS_DOUBLE); 
ssSetOutputPortWidth(S, 74, 1); 
ssSetOutputPortDataType(S, 75, SS_UINT32); 
ssSetOutputPortWidth(S, 75, 1); 
ssSetOutputPortDataType(S, 76, SS_UINT8); 
ssSetOutputPortWidth(S, 76, 1); 
ssSetOutputPortDataType(S, 77, SS_UINT8); 
ssSetOutputPortWidth(S, 77, 1); 
ssSetOutputPortDataType(S, 78, SS_UINT8); 
ssSetOutputPortWidth(S, 78, 1); 
ssSetOutputPortDataType(S, 79, SS_UINT8); 
ssSetOutputPortWidth(S, 79, 1); 
ssSetOutputPortDataType(S, 80, SS_UINT8); 
ssSetOutputPortWidth(S, 80, 1); 
ssSetOutputPortDataType(S, 81, SS_UINT8); 
ssSetOutputPortWidth(S, 81, 1); 
ssSetOutputPortDataType(S, 82, SS_UINT8); 
ssSetOutputPortWidth(S, 82, 1); 
ssSetOutputPortDataType(S, 83, SS_UINT8); 
ssSetOutputPortWidth(S, 83, 1); 
ssSetOutputPortDataType(S, 84, SS_UINT8); 
ssSetOutputPortWidth(S, 84, 1); 
ssSetOutputPortDataType(S, 85, SS_UINT8); 
ssSetOutputPortWidth(S, 85, 1); 
/* CAPTURE MESSAGES 7*/ 
ssSetOutputPortDataType(S, 86, SS_BOOLEAN); 
ssSetOutputPortWidth(S, 86, 1); 
ssSetOutputPortDataType(S, 87, SS_DOUBLE); 
ssSetOutputPortWidth(S, 87, 1); 
ssSetOutputPortDataType(S, 88, SS_UINT32); 
ssSetOutputPortWidth(S, 88, 1); 
ssSetOutputPortDataType(S, 89, SS_UINT8); 
ssSetOutputPortWidth(S, 89, 1); 
ssSetOutputPortDataType(S, 90, SS_UINT8); 
ssSetOutputPortWidth(S, 90, 1); 
ssSetOutputPortDataType(S, 91, SS_UINT8); 
ssSetOutputPortWidth(S, 91, 1); 
ssSetOutputPortDataType(S, 92, SS_UINT8); 
ssSetOutputPortWidth(S, 92, 1); 
ssSetOutputPortDataType(S, 93, SS_UINT8); 
ssSetOutputPortWidth(S, 93, 1); 
ssSetOutputPortDataType(S, 94, SS_UINT8); 
ssSetOutputPortWidth(S, 94, 1); 
ssSetOutputPortDataType(S, 95, SS_UINT8); 
ssSetOutputPortWidth(S, 95, 1); 
ssSetOutputPortDataType(S, 96, SS_UINT8); 
ssSetOutputPortWidth(S, 96, 1); 
ssSetOutputPortDataType(S, 97, SS_UINT8); 
ssSetOutputPortWidth(S, 97, 1); 
ssSetOutputPortDataType(S, 98, SS_UINT8); 
ssSetOutputPortWidth(S, 98, 1); 
/* CAPTURE MESSAGES 8*/ 
ssSetOutputPortDataType(S, 99, SS_BOOLEAN); 
ssSetOutputPortWidth(S, 99, 1); 
ssSetOutputPortDataType(S, 100, SS_DOUBLE); 
ssSetOutputPortWidth(S, 100, 1); 
ssSetOutputPortDataType(S, 101, SS_UINT32); 
ssSetOutputPortWidth(S, 101, 1); 
ssSetOutputPortDataType(S, 102, SS_UINT8); 
ssSetOutputPortWidth(S, 102, 1); 
ssSetOutputPortDataType(S, 103, SS_UINT8); 
ssSetOutputPortWidth(S, 103, 1); 
ssSetOutputPortDataType(S, 104, SS_UINT8); 
ssSetOutputPortWidth(S, 104, 1); 
ssSetOutputPortDataType(S, 105, SS_UINT8); 
ssSetOutputPortWidth(S, 105, 1); 
ssSetOutputPortDataType(S, 106, SS_UINT8); 
ssSetOutputPortWidth(S, 106, 1); 
ssSetOutputPortDataType(S, 107, SS_UINT8); 
ssSetOutputPortWidth(S, 107, 1); 
ssSetOutputPortDataType(S, 108, SS_UINT8); 
ssSetOutputPortWidth(S, 108, 1); 
ssSetOutputPortDataType(S, 109, SS_UINT8); 
ssSetOutputPortWidth(S, 109, 1); 
ssSetOutputPortDataType(S, 110, SS_UINT8); 
ssSetOutputPortWidth(S, 110, 1); 
ssSetOutputPortDataType(S, 111, SS_UINT8); 
ssSetOutputPortWidth(S, 111, 1); 
