%RTWMAKECFG adds include and source directories to rtw make files.
%  
%  This file was autmomatic generated by dSPACE Blockset
%  To include the RTI-Sources to the RTW-Build-Prozess the path to this
%  file has to be part of the matlab-search-path
%  
%   See also RTWMAKECFG, MAKE_RTW, PATH.
%  
%  Copyright (c) 2015 by dSPACE GmbH, GERMANY
%  
function makeInfo = rtwmakecfg()

makeInfo.includePath = {'..\RTICANMM_FILES', cd};
makeInfo.sourcePath  = {'..\RTICANMM_FILES', cd};
                                                                   
StaticSourceDir = which('dsRTICANMMGlobals.h');                  
if ~isempty(StaticSourceDir)                                       
  makeInfo.includePath{end+1} = fileparts(StaticSourceDir);        
end
                                                              
Type = rtimmsu_private('fcnlib', 'rttype', gcs);               
if (strcmp(Type, 'DSOFFSIM'))                                    
    StaticSourceDir = which('dsstd.h');                          
    if ~isempty(StaticSourceDir)                                   
      makeInfo.includePath{end+1} = fileparts(StaticSourceDir);    
    end                                                            
                                                                   
    StaticSourceDir = which('dscan.h');                          
    if ~isempty(StaticSourceDir)                                   
      makeInfo.includePath{end+1} = fileparts(StaticSourceDir);    
    end                                                            
                                                                   
    StaticSourceDir = which('DsJ1939Node.h');                    
    if ~isempty(StaticSourceDir)                                   
      makeInfo.includePath{end+1} = fileparts(StaticSourceDir);    
    end                                                            
    StaticSourceDir = which('DSJ1939_Host');                     
    if ~isempty(StaticSourceDir)                                   
      makeInfo.linkLibsObjs{1} = StaticSourceDir;                  
    end                                                            
                                                                   
    StaticSourceDir = which('dscan');                            
    if ~isempty(StaticSourceDir)                                   
      makeInfo.linkLibsObjs{end+1} = StaticSourceDir;              
    end                                                            
end                                                                
